---
services:
  aml-seed-det:
    build:
      context: .
      dockerfile: Dockerfile
    # command: ["/bin/sh", "-c", "hypercorn -b :8080 app:app"]
    command: bash -c './startup.sh'
    user: 1000:1000
    ports:
      - "12380:5001"
      - "12381:8883"
      - "12382:8888"
    env_file:
      - .env
    environment:
      - PORT=8080
      - AZUREML_MODEL_DIR=/app/artifacts
    # volumes:
    #   - ../AzureMLSeedDet:/app
